simplified alphabet annotation macro definition
trevorcampbell/shortex pull request #7
Opened 2021-07-07 20:59 UTC by jnegrea

I made macros to automatically generate annotation macros for lists of characters or latex macros (for greek letters)... 
I implemented all existing annotations in this way. 
A couple annotation types had too many exceptions so I changed the annotation prefix so there would be fewer exceptions.
I think this should be abstracted further because i) there is a combinatorial explosion of possible annotation combinations and ii) this defines thousands of macros, most of which will not be used, and im not sure whether this is ideal or affects latex performance

2021-07-07 21:17 UTC, jhuggins requested changes
Nice! You'll need to pull the latest changes from `master`? I just merged my PR.

2021-07-07 21:17 UTC, jhuggins commented on shortex.sty
> +\newcommand{\charalphabetmacro}[3]{
Could you add a comment describing what this does?

2021-07-07 21:17 UTC, jhuggins commented on shortex.sty
> +\newcommand{\texalphabetmacro}[3]{
Comment here too

2021-07-07 21:17 UTC, jhuggins commented on example-jn.tex
> +\documentclass{article}
Could you add these to `example.tex`?

2021-07-07 21:38 UTC, jnegrea commented
i pushed resolutions to @jhuggins requests to the branch, do i need to merge the pull request to update it? or does that push it to master?

2021-07-08 02:23 UTC, jhuggins approved these changes
Nice! I think this is fine to merge after deleting `example-jn.*`

2021-07-08 02:25 UTC, jhuggins commented
> i pushed resolutions to @jhuggins requests to the branch, do i need to merge the pull request to update it? or does that push it to master?

Yup. Merge the pull request, then you can delete your branch.

2021-07-08 02:43 UTC, merged